#!/bin/bash

# sleep until instance is ready
until [[ -f /var/lib/cloud/instance/boot-finished ]]; do
	  sleep 1
  done

  # install haxproxy
  sudo apt-get update
  sudo apt-get -y install haproxy
  sudo haproxy version

  # make sure nginx is started
  service nginx start

